use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

target 'FlexibleAlignButton_Example' do
    pod 'FlexibleAlignButton', :path => '../'

  target 'FlexibleAlignButton_Tests' do
    inherit! :search_paths

    
  end
end
